### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by ashucoder9**
Was going through the docs and felt the document needed a bit of polishing.

### CODE REVIEW

**Comment by NoahMaizels** [comment]
I definitely see a lot of really good improvements here! Just one thing, there are some Notion links which need to be changed to the relative links to our own docs. Could you please change that? Thanks for putting the thought and work into this PR, I'd love to get it added soon. Thank you!

**Comment by ashucoder9** [comment]
Yeah sure, will update them

**Comment by ashucoder9** [comment]
Updated the notion links @NoahMaizels

**Comment by significance** [comment]
hey @ashucoder9 thanks so much for your contribution! we're in the process of rewriting this internally at the moment. will close this for now, but your suggestions will be folded into our end result. thanks for being part of the swarm! 🐝

**Pull request closed without merging**
