### PR TITLE
fix: add main net network-id set info

### PR DESCRIPTION
**Pull request by moremorefun**
`network-id` defualt in source code is `10`,
but run in mainnet, it should be set to `1`.

### CODE REVIEW

**Comment by attila-lendvai** [comment]
oh well. this will be fixed in bee in a couple of days, but let's just include this for the time being, and then delete it once the fix is released...

**Review by attila-lendvai — APPROVED** [review]

**Comment by moremorefun** [comment]
the default value will be set to `1` in yaml file and source code?

**Comment by attila-lendvai** [comment]
> the default value will be set to `1` in yaml file and source code?

the source code will default to `1` if there's no entry in the yaml file.

currently bee defaults to 10 if `network-id` is not provided at all.

**Comment by moremorefun** [comment]
If network-id default set as 1, that means the mainnet in source code will default set to true, right?

**Comment by attila-lendvai** [comment]
yes, that is my understanding. but let's just wait until the commits land in the bee repo, and then we'll update the docs.

**Comment by moremorefun** [comment]
Make sence.

The default configuration should be adapted to run on mainnet and not testnet

**Pull request merged**
