### PR TITLE
reword "we" and "ours" in the intro/landing page

### PR DESCRIPTION
**Pull request by wendydv1989**
Tried to edit the "we" and "ours"

### CODE REVIEW

**Review by attila-lendvai — CHANGES_REQUESTED** [review]
please remove the `package-lock.json` changes from the commit. (but keep it in the .gitignore)

the stylistic changes look reasonable to me, but i'm not the one to decide about those. you may want to wait for more feedback from others before updating the PR.

**Comment by attila-lendvai** [comment]
i have updated this commit by removing the (now conflicting) changes to `package-lock.json` and `.gitignore`, and pushed the commit into my fork (i cannot or don't know how to update this PR):

https://github.com/attila-lendvai/bee-docs/tree/homepage-copyedit

let me know how to proceed. if that's the simplest, i can open a new PR (commit author remained the same).

**Comment by significance** [comment]
@attila-lendvai yes please that would be wonderful! cc: @wendydv1989

**Comment by attila-lendvai** [comment]
superseded by: https://github.com/ethersphere/bee-docs/pull/223

**Pull request closed without merging**
