### PR TITLE
Creating a terminology section.

### PR DESCRIPTION
**Pull request by centerorbit**
This section explains some of the core concepts and terms used throughout the rest of the documentation. As Bee is aiming to target all people, and not just those already familiar with blockchain technology, it can be helpful to provide a bit of extra context.

### CODE REVIEW

**Comment by significance** [comment]
this is great @centerorbit - there is also an *extensive* glossary in the book

did you want to continue? i do like the idea of a glossary in the docs!

**Comment by centerorbit** [comment]
> this is great @centerorbit - there is also an _extensive_ glossary in the book
> 
> did you want to continue? i do like the idea of a glossary in the docs!

Hey! Sorry for the delay, yes I'm planning on finishing this; I've just been sidetracked by other work. I should be able to wrap this up in the next couple days. (weekend is here, which frees me up for this.)

**Comment by centerorbit** [comment]
@significance I finished the last sections and rebased the changes. It's ready to be merge!

Thanks for mentioning the glossary in the book. I did use that to provide some more context in my later sections.

**Comment by significance** [comment]
@centerorbit apologies for the slow response this went under the radar 😌 

could you rebase over master and add this to the 'find out more' section please?

then i'll merge.

great work! 🌟

**Review by significance — APPROVED** [review]
thanks for your efforts here dude! sorry for the slooow merge 🐌

**Pull request merged**
