### PR TITLE
Initial editorial review

### PR DESCRIPTION
**Pull request by attila-lendvai**
original work by @mfw78 <mfw78@chasingseed.com>

things i've done:

- resolved several non-trivial merge conflicts
- open this PR instead of the original https://github.com/ethersphere/bee-docs/pull/196 (didn't know how to force push into that one)
- audited the Swarm/swarm capitalization, and have undone most of them (@mfw78 please take a look if you're planning to submit more content! i'll add a CODING.md later with a few words about it).
- very sparsely run through the changes

@sig or whoever will review this: it would be nice if you could run through the diff before merging!

### CODE REVIEW

**Comment by attila-lendvai** [comment]
TODO: audit the capitalization of Swarm and undo where needed.

**Comment by significance** [comment]
blimey @attila-lendvai! great work! might take a little while but yes i will indeed 👾

**Comment by mfw78** [comment]
@attila-lendvai Thanks for the heads up on the forthcoming `CODING.md`. I'll be sure to be as close as possible to the agreed grammar :+1:

**Review by significance — APPROVED** [review]
@attila-lendvai @mfw78 have scanned this and it looks great - thanks both for amazing effort. need to make some more changes so am going to merge now to avoid further conflicts pending reading over everything myself. great work! 💥

**Pull request merged**
